/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 src/app/deonslab.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/deonslab.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Plane.geometry} material={materials.M_Basic} />
      <mesh geometry={nodes.PC_Case.geometry} material={materials.M_Basic} scale={[0.386, 1, 1]} />
      <mesh geometry={nodes.BackFan.geometry} material={materials.M_Basic} scale={[0.386, 1, 1]} />
      <group position={[0, 0, -2.098]}>
        <mesh geometry={nodes.Cube003.geometry} material={materials.M_Basic} />
        <mesh geometry={nodes.Cube003_1.geometry} material={materials.M_Screen1} />
      </group>
      <mesh geometry={nodes.Knobs.geometry} material={materials.M_Basic} />
      <mesh geometry={nodes.Speaker1.geometry} material={materials.M_Basic} />
      <mesh geometry={nodes.AudioInterface.geometry} material={materials.M_Basic} position={[0, 1.422, 1.43]} scale={[0.178, 0.087, 0.272]} />
      <mesh geometry={nodes.KeyboardBse.geometry} material={materials.M_Basic} scale={0.283} />
      <mesh geometry={nodes.KeyBoardKeys.geometry} material={materials.M_Basic} />
      <mesh geometry={nodes.Mouse.geometry} material={materials.M_Basic} />
      <mesh geometry={nodes.CPU.geometry} material={materials.M_Basic} scale={[0.386, 1, 1]} />
      <mesh geometry={nodes.Motherboard.geometry} material={materials.M_Basic} scale={0.283} />
      <group position={[0, 0, -3.725]}>
        <mesh geometry={nodes.Cube010.geometry} material={materials.M_Basic} />
        <mesh geometry={nodes.Cube010_1.geometry} material={materials.M_Screen1} />
      </group>
      <group position={[1.808, 0, -3.725]}>
        <mesh geometry={nodes.Cube011.geometry} material={materials.M_Basic} />
        <mesh geometry={nodes.Cube011_1.geometry} material={materials.M_Screen1} />
      </group>
      <mesh geometry={nodes.Speaker2.geometry} material={materials.M_Basic} position={[0, 0, -4.035]} />
      <mesh geometry={nodes.PCFans.geometry} material={materials.M_Basic} scale={[0.386, 1, 1]} />
    </group>
  )
}

useGLTF.preload('/deonslab.gltf')
