/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 src/app/deonslab.gltf 
*/

import React, { useRef } from "react";
import { useGLTF, useTexture } from "@react-three/drei";
import * as THREE from "three";

export function DesktopModel({ goToProjects, props }) {
  const { nodes, materials } = useGLTF("/deonslab.gltf");

  const texture = useTexture("/deonslabcolourpallete.jpg");

  const switchTo = (e) => {
    switch (e) {
      case "projects":
        goToProjects();
        break;

      default:
        break;
    }
  };
  const baseMaterial = new THREE.MeshStandardMaterial({
    map: texture,
    roughness: 1,
    metalness: 0.2,

    // envMapIntensity: 0.6,
  });
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Plane.geometry} material={baseMaterial} />
      <mesh
        geometry={nodes.PC_Case.geometry}
        material={baseMaterial}
        scale={[0.386, 1, 1]}
      />
      <mesh
        geometry={nodes.BackFan.geometry}
        material={baseMaterial}
        scale={[0.386, 1, 1]}
      />
      <group position={[0, 0, -2.098]}>
        <mesh geometry={nodes.Cube003.geometry} material={baseMaterial} />
        <mesh
          geometry={nodes.Cube003_1.geometry}
          material={materials.M_Screen1}
        />
      </group>
      <mesh geometry={nodes.Knobs.geometry} material={baseMaterial} />
      <mesh geometry={nodes.Speaker1.geometry} material={baseMaterial} />
      <mesh
        geometry={nodes.AudioInterface.geometry}
        material={baseMaterial}
        position={[0, 1.422, 1.43]}
        scale={[0.178, 0.087, 0.272]}
      />
      <mesh
        geometry={nodes.KeyboardBse.geometry}
        material={baseMaterial}
        scale={0.283}
      />
      <mesh geometry={nodes.KeyBoardKeys.geometry} material={baseMaterial} />
      <mesh geometry={nodes.Mouse.geometry} material={baseMaterial} />
      <mesh
        geometry={nodes.CPU.geometry}
        material={baseMaterial}
        scale={[0.386, 1, 1]}
      />
      <mesh
        geometry={nodes.Motherboard.geometry}
        material={baseMaterial}
        scale={0.283}
      />
      <group position={[0, 0, -3.725]}>
        <mesh geometry={nodes.Cube010.geometry} material={baseMaterial} />
        <mesh
          geometry={nodes.Cube010_1.geometry}
          material={materials.M_Screen1}
        />
      </group>
      <group position={[1.808, 0, -3.725]} onClick={() => switchTo("projects")}>
        <mesh geometry={nodes.Cube011.geometry} material={baseMaterial} />
        <mesh
          geometry={nodes.Cube011_1.geometry}
          material={materials.M_Screen1}
        />
      </group>
      <mesh
        geometry={nodes.Speaker2.geometry}
        material={baseMaterial}
        position={[0, 0, -4.035]}
      />
      <mesh
        geometry={nodes.PCFans.geometry}
        material={baseMaterial}
        scale={[0.386, 1, 1]}
      />
    </group>
  );
}

useGLTF.preload("/deonslab.gltf");
