import NavBar from "./Components/NavBar";
import "./globals.scss";

export const metadata = {
  title: "Deon's Lab",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
